version: '3'
services:
  janusgraph-docker:
    image: docker.io/janusgraph/janusgraph:1.0.1-20240806-071648.ba2d662
    container_name: ergo_janusgraph
    user: root
    volumes:
      - "./docker/janusgraph/:/etc/opt/janusgraph/:ro"
      - "data_index:/var/lib/janusgraph/index"
    ports:
      - "8182:8182"
    depends_on:
     - cass-docker
    links:
     - cass-docker
  cass-docker:
    image: docker.io/cassandra:latest
    container_name: ergo_cass
    user: root
    environment:
     - CASSANDRA_START_RPC=true
    volumes:
      - "data_cass:/var/lib/cassandra"
  ergo-docker:
    image: localhost/rdf4j:ergo
    container_name: ergo_rdf4j
    user: root
    build:
      context: .
      dockerfile: docker/rdf4j/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "data_rdf4j:/root/.RDF4J/"
      - "bulkloading_data:/usr/local/tomcat/bulkloading/data"
      - "bulkloading/bulkload.properties:/usr/local/tomcat/bulkload.properties"
    depends_on:
     - cass-docker
     - janusgraph-docker
    links:
     - cass-docker
     - janusgraph-docker
