version: '3'
services:
  janusgraph-docker:
    image: docker.io/janusgraph/janusgraph:0.4.0
    container_name: ergo_janusgraph
    user: root
    volumes:
      - "./docker/janusgraph/:/etc/opt/janusgraph/:Z"
      - "./docker/data/index:/var/lib/janusgraph/index:Z"
    ports:
      - "8182:8182"
    depends_on:
     - cass-docker
    links:
     - cass-docker
  cass-docker:
    image: docker.io/cassandra:2.2.16
    container_name: ergo_cass
    user: root
    environment:
     - CASSANDRA_START_RPC=true
    volumes:
      - "./docker/data/cass:/var/lib/cassandra:Z"
  ergo-docker:
    image: localhost/rdf4j:ergo
    container_name: ergo_rdf4j
    user: root
    build:
      context: .
      dockerfile: docker/rdf4j/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./docker/data/rdf4j:/root/.RDF4J/:Z"
      - "./docker/bulkloading/data:/usr/local/tomcat/bulkloading/data:Z"
      - "./docker/bulkloading/bulkload.properties:/usr/local/tomcat/bulkload.properties:Z"
    depends_on:
     - cass-docker
     - janusgraph-docker
    links:
     - cass-docker
     - janusgraph-docker
