- name: Deploy JanusGraph and RDF4J with Podman
  hosts: localhost
  tasks:
    - name: Create necessary volumes
      containers.podman.podman_volume:
        name: "{{ item }}"
        state: present
      loop:
        - data_index
        - data_rdf4j
        - bulkloading_data

    - name: Run JanusGraph container
      containers.podman.podman_container:
        name: ergo_janusgraph
        image: docker.io/janusgraph/janusgraph:1.0.1-20240806-071648.ba2d662
        state: started
        user: root
        privileged: true
        volumes:
          - "data_index:/var/lib/janusgraph/index"
        ports:
          - "8182:8182"

    - name: Wait for Janusgraph to initialize (1 minute delay)
      wait_for:
        timeout: 60

    - name: Run RDF4J container
      containers.podman.podman_container:
        name: ergo_rdf4j
        image: ghcr.io/abc-rp/expressive-reasoning-graph-store:rdf4j_af7caab
        state: started
        user: root
        ports:
          - "8080:8080"
        volumes:
          - "data_rdf4j:/root/.RDF4J/"
          - "bulkloading_data:/usr/local/tomcat/bulkloading/data"
          - "{{ playbook_dir }}/docker/bulkloading/bulkload.properties:/usr/local/tomcat/bulkload.properties"
