name: Build and Push Docker image
on:
  pull_request:
    branches:
      - master

env:
  DOCKERFILE_PATH: "docker/rdf4j/Dockerfile" # Set your Dockerfile path here

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract branch name
        run: echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV

      - name: Log in to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and tag image
        run: |
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          TAG="rdf4j_${COMMIT_SHA}"
          docker build -t ghcr.io/${{ github.repository }}:$TAG -f ${{ env.DOCKERFILE_PATH }} .
          echo "tag=$TAG" >> $GITHUB_ENV

      - name: Push image to GHCR
        run: docker push ghcr.io/${{ github.repository }}:${{ env.tag }}
